<?php
function rd_custom_post_types_register() {

  $post_types = [
    'services' => [
      'supports' => [ 'title', 'revisions', 'editor', 'author', 'excerpt', 'thumbnail' ],
      'public' => true,
      'show_in_rest' => true,
      'has_archive' => false,
      'menu_position' => 5,
      'show_in_menu' => true,
      'menu_icon' => 'dashicons-clipboard',
      'rewrite' => false,
      'labels' => [
        'name' => 'Services',
        'singular_name' => 'Service',
        'add_new' => 'Add New Service',
        'add_new_item' => 'Add New Service',
        'edit_item' => 'Edit Service',
        'new_item' => 'New Service',
        'view_item' => 'View Service',
        'view_items' => 'View Services',
        'search_items' => 'Search Services',
        'not_found' => 'No Services found',
        'not_found_in_trash' => 'No Services found in trash',
        'parent_item_colon' => 'Parent Services',
        'all_items' => 'All Services',
        'archives' => 'Services Archives',
        'attributes' => 'Services Attributes',
        'insert_into_item' => 'Insert into Service',
        'uploaded_to_this_item' => 'Uploaded to this Service',
        'filter_items_list' => 'Filter Services list',
        'items_list_navigation' => 'Services list navigation',
        'items_list' => 'Services list',
        'item_published' => 'Service published',
        'item_published_privately' => 'Service published privately',
        'item_reverted_to_draft' => 'Service reverted to draft',
        'item_scheduled' => 'Service scheduled',
        'item_updated' => 'Service updated',
      ],
    ],
    'documents' => [
      'supports' => [ 'title', 'revisions', 'editor', 'author', 'excerpt', 'thumbnail' ],
      'public' => true,
      'show_in_rest' => true,
      'has_archive' => false,
      'menu_position' => 5,
      'show_in_menu' => true,
      'menu_icon' => 'dashicons-networking',
      'rewrite' => [ 'slug' => 'documents', 'with_front' => false ],
      'labels' => [
        'name' => 'Documents',
        'singular_name' => 'Document',
        'add_new' => 'Add New Document',
        'add_new_item' => 'Add New Document',
        'edit_item' => 'Edit Document',
        'new_item' => 'New Document',
        'view_item' => 'View Document',
        'view_items' => 'View Documents',
        'search_items' => 'Search Documents',
        'not_found' => 'No Documents found',
        'not_found_in_trash' => 'No Documents found in trash',
        'parent_item_colon' => 'Parent Document',
        'all_items' => 'All Documents',
        'archives' => 'Document Archives',
        'attributes' => 'Document Attributes',
        'insert_into_item' => 'Insert into Document',
        'uploaded_to_this_item' => 'Uploaded to this Document',
        'filter_items_list' => 'Filter Documents list',
        'items_list_navigation' => 'Documents list navigation',
        'items_list' => 'Documents list',
        'item_published' => 'Document published',
        'item_published_privately' => 'Document published privately',
        'item_reverted_to_draft' => 'Document reverted to draft',
        'item_scheduled' => 'Document scheduled',
        'item_updated' => 'Document updated',
      ],
    ],
    'store' => [
      'supports' => [ 'title', 'revisions', 'editor', 'author', 'excerpt', 'thumbnail' ],
      'public' => true,
      'show_in_rest' => true,
      'has_archive' => false,
      'menu_position' => 5,
      'show_in_menu' => true,
      'menu_icon' => 'dashicons-cart',
      'rewrite' => [ 'slug' => 'store', 'with_front' => false ],
      'labels' => [
        'name' => 'Store',
        'singular_name' => 'Store Item',
        'add_new' => 'Add New Store Item',
        'add_new_item' => 'Add New Store Item',
        'edit_item' => 'Edit Store Item',
        'new_item' => 'New Store Item',
        'view_item' => 'View Store Item',
        'view_items' => 'View Store Items',
        'search_items' => 'Search Store Items',
        'not_found' => 'No Store Items found',
        'not_found_in_trash' => 'No Store Items found in trash',
        'parent_item_colon' => 'Parent Store Item',
        'all_items' => 'All Store Items',
        'archives' => 'Store Item Archives',
        'attributes' => 'Store Item Attributes',
        'insert_into_item' => 'Insert into Store Item',
        'uploaded_to_this_item' => 'Uploaded to this Store Item',
        'filter_items_list' => 'Filter Store Items list',
        'items_list_navigation' => 'Store Items list navigation',
        'items_list' => 'Store Items list',
        'item_published' => 'Store Item published',
        'item_published_privately' => 'Store Item published privately',
        'item_reverted_to_draft' => 'Store Item reverted to draft',
        'item_scheduled' => 'Store Item scheduled',
        'item_updated' => 'Store Item updated',
      ],
    ],
  ];

  foreach ( $post_types as $key => $post_type ) {
    register_post_type($key, $post_type);
  }

}

add_action( 'init', 'rd_custom_post_types_register', 0 );